### ISSUE TITLE
how to change api endpoint for getting value & symbol name

### ISSUE THREAD

**Issue by lakhank295** [ChartIQ/chartiq-angular-app#5]
Hi, I've cloned this project & trying to customize the component, I searched in all services & components but not found any API call code. I am a bit confused that how can I change the symbol name so that based on user input it should get data & even I wanted to change the API.
please guide me

**Comment by RMcNeely** [comment]
Hi @lakhank295, can you please contact support@chartiq.com and so that we can help you.
